# fly.toml app configuration file generated for wattpm-demo on 2024-09-28T21:58:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wattpm-demo'
primary_region = 'sin'

[build]

[http_service]
internal_port = 3042
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[checks]
[checks.api_health_check]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/"
port = 3042
timeout = "10s"
type = "http"


[[vm]]
size = 'shared-cpu-1x'
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
